#!/bin/bash

EMAIL='def@456.com'
PASSWORD='def456'

BASE_URL="http://localhost:8080"
URL="${BASE_URL}/sign-in"

url() {

  CONTENT_TYPE="application/x-www-form-urlencoded"

  curl ${URL} \
  --include \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --data-urlencode "credentials[email]=${EMAIL}" \
  --data-urlencode "credentials[password]=${PASSWORD}"

}

json() {

  CONTENT_TYPE="application/json"

  curl ${URL} \
  --include \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --data "{
    \"credentials\": {
      \"email\": \"${EMAIL}\",
      \"password\": \"${PASSWORD}\"
    }
  }"

}

json

echo
